const conditions = [
  "ADD",
  "Accupuncture",
  "Addiction Counseling",
  "ADHD",
  "Ankle/foot pain",
  "Anxiety",
  "Autism",
  "Adjustment",
  "Apraxia",
  "Aphasia",
  "Back pain",
  "Breastfeeding Issues",
  "Butteyko breathing therapist",
  "Calorie Budget",
  "Certified hand therapist",
  "Chair Massage",
  "Cognitive Behavioral Therapy (CBT)",
  "Counseling",
  "Couples Counseling",
  "Cranio-Sacral Treatment",
  "Deep Tissue",
  "Depression",
  "Diabetic Training",
  "Diet Development",
  "Swallowing",
  "Dizziness",
  "Ear pain",
  "EDMR",
  "Electric Stimulation",
  "Electric Acupuncture",
  "Energetic",
  "Energy Healing",
  "Equipment Training (Durable Medical Equipment)",
  "Family Counseling",
  "Fecal Incontinence",
  "Gait Training",
  "Hand pain",
  "Headaches",
  "Healing Touch",
  "Health and Wellness",
  "Health Coaching",
  "Health Counseling",
  "Hip pain",
  "Hot Stone",
  "Infant Feeding Issues",
  "Knee pain",
  "Laser Treatment",
  "Leg pain",
  "Low back pain",
  "Lymphadema",
  "Manual Therapy",
  "Marriage Counseling",
  "Massage",
  "Mid back pain",
  "Migraines",
  "Mindfulness Training",
  "Mood swings",
  "Myofascial Release",
  "Neck pain",
  "Nutrition Coaching",
  "Occupational therapy",
  "Oral myofunctional therapist",
  "Organic Products",
  "Overeating Counseling",
  "Pain",
  "Pelvic Floor Pain",
  "Physical therapy",
  "Pre-marital counseling",
  "PTSD",
  "Raindrop Massage",
  "Reflexology",
  "Reiki",
  "Reiki Healing",
  "Snoring",
  "Speech Disorder",
  "Speech therapist",
  "Sports Massage",
  "Sprain",
  "Strain",
  "Stress Urinary Incontinence",
  "Thai",
  "Theta Healing",
  "TMJ massage",
  "TMJ/Jaw pain",
  "Trigger Point Massage",
  "Ultrasound",
  "Vertigo",
  "Weight Loss",
  "Young Living Products",
]

export default conditions
