const services = {
  "Common Physical Therapy Services/Practices": [
    "All painful conditions",
    "Myofascial Release",
    "Therapeutic Exercise",
    "Stretching",
    "Ultrasound",
    "Electrical Stimulation",
    "Traction",
    "Cranio-Sacral Therapy",
    "Pelvic Floor Rehab",
    "Stress Urinary Incontinence",
    "Vestibular Rehab",
    "Dizziness",
    "Lymphadema",
    "Laser Treatment",
    "Wound Care",
    "Respiratory Therapy",
    "Neurological Rehab",
    "Muscle Energy Technique",
    "Instrument Assisted Soft Tissue Mobilization",
    "Dry Needling",
    "Iontophoresis",
    "Manual Therapy",
    "Ergonomic Training/Evaluation",
    "Gait training",
    "Therapeutic Activity",
    "Laser Treatment",
    "Ultrasound",
  ],
  "Common Occupational Therapy/Practices": [
    "Certified Hand Therapist",
    "Manual therapy",
    "Splinting",
    "Exercise",
    "Intrinsic Activities of Daily Living (IADLs)",
    "Equipment Training (Durable Medical Equipment)",
    "Laser Treatment",
    "Electrical Stimulation",
    "Laser treatment",
    "Paraffin wax",
  ],
  "Common Counseling/Talk Therapies": [
    "Cognitive Behavior Therapy",
    "Couples Counseling",
    "Family Counseling",
    "ADD/ADHD",
    "Autism",
    "Social skills",
    "EDMR",
    "Anxiety/depression",
    "Addiction",
  ],
  "Common Speech Therapy Practices/Therapies": [
    "Apraxia",
    "Aphasia",
    "Butteyho breathing",
    "Oral myofunctional therapy",
    "Speech disorder",
    "Stutter",
    "Snoring",
  ],
  "Common Chiropractor Practices/Services": [
    "Adjustment",
    "Manipulation",
    "Active Release Therapy (ART)",
    "Sacral Occiput Therapy (SOT)",
    "Manual therapy",
    "Massage",
    "Electrical stimulation",
    "Acupuncture",
    "Electric Acupuncture",
  ],
  "Common Nutritionist/Dietician Practices/Services": [
    "Health Counseling",
    "Diet Counseling",
    "Nutrition counseling",
    "Calorie Budget",
    "Diet Development",
    "Diabetic Counseling",
    "Thyroid Counseling",
  ],
  "Common Licensed Massage Therapist Services": [
    "Sweedish Massage",
    "Effleurage",
    "Cranial-Sacral Therapy",
    "Active-Release Therapy",
    "Myofascial Release Therapy",
    "Lymphadema Therapy",
    "Pre-Natal Massage/Pregnancy",
    "Deep Tissue",
    "Hot Stone",
    "Thai",
    "Energetic",
    "Reiki",
    "Healing Touch",
    "Theta Healing",
    "Reflexology",
    "Sports Massage",
    "TMJ massage",
    "Trigger Point Massage",
    "Chair Massage",
    "Raindrop Massage",
    "Young Living Products",
    "Organic Products",
  ],
}

export default services
